import { Student, Preference, Hostel, Room, AllocationRequest } from './types';

export const student: Student = {
  name: 'Victory Okafor',
  regNo: 'CSC/22/1048',
  department: 'Computer Science',
  faculty: 'Computing & Information Technology',
  level: '300 Level',
  initials: 'VO',
  allocationStatus: 'Allocated',
  room: 'B-214',
  assignedHostel: 'Mango House',
  matchScore: 94,
  paymentStatus: 'Cleared',
  email: 'v.okafor@campus.edu.ng',
  phone: '+234 812 345 6789',
  emergencyContact: 'Mrs. Ngozi Okafor (Mother)',
  emergencyPhone: '+234 803 111 2233',
  gender: 'Female',
  stateOfOrigin: 'Enugu State',
  bio: 'Junior year software engineering student researching distributed systems. Quiet night study habits.',
};

export const initialPreference: Preference = {
  roomType: 'Double room',
  floor: '2nd floor',
  quietHours: '10:00 pm to 6:00 am',
  roommateRegNo: 'CSC/22/1192',
  studyHabit: 'Night owl (Study after 8pm)',
  specialNeeds: 'None',
};

export const hostels: Hostel[] = [
  {
    name: 'Mango House',
    block: 'Block B',
    location: 'North campus · 4 min walk to Science Complex',
    price: 185000,
    capacity: 2,
    available: 8,
    gender: 'Mixed Floors',
    description: 'A modern, sunlit hostel close to science lecture halls with 24/7 solar backup and quiet study lounges.',
    amenities: ['Solar Study Desk', 'Wardrobe', 'High-speed Wi-Fi', 'Water Heater', 'Kitchenette'],
    accent: 'peach',
  },
  {
    name: 'Aster Court',
    block: 'Block D',
    location: 'Central campus · 7 min walk to Main Library',
    price: 215000,
    capacity: 2,
    available: 3,
    gender: 'Female Block',
    description: 'Ensuite dual-occupancy rooms with private bathrooms, central courtyard, and dedicated laundry facilities.',
    amenities: ['Ensuite Bathroom', 'Balcony', 'Study desk', 'Laundry Area', 'Backup Power'],
    accent: 'sage',
  },
  {
    name: 'The Lantern',
    block: 'Block A',
    location: 'East campus · 10 min walk to Student Union',
    price: 145000,
    capacity: 4,
    available: 16,
    gender: 'Male Block',
    description: 'Spacious quad rooms fostering collaborative campus life with shared recreational rooms and dining commons.',
    amenities: ['Shared Kitchen', 'Courtyard', 'Wi-Fi', 'Security CCTV', 'Reading Hall'],
    accent: 'sand',
  },
];

export const rooms: Room[] = [
  // Block B (Mango House)
  { number: 'B-101', block: 'Block B', floor: 1, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'B-102', block: 'Block B', floor: 1, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Chinedu O.', 'Tariq A.'] },
  { number: 'B-103', block: 'Block B', floor: 1, status: 'Maintenance', type: 'Single', capacity: 1, occupants: [] },
  { number: 'B-104', block: 'Block B', floor: 1, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'B-105', block: 'Block B', floor: 1, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Emeka K.', 'Samuel P.'] },
  { number: 'B-201', block: 'Block B', floor: 2, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'B-202', block: 'Block B', floor: 2, status: 'Occupied', type: 'Single', capacity: 1, occupants: ['Ibrahim G.'] },
  { number: 'B-203', block: 'Block B', floor: 2, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'B-214', block: 'Block B', floor: 2, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Victory Okafor', 'Farouk M.'] },
  { number: 'B-205', block: 'Block B', floor: 2, status: 'Available', type: 'Single', capacity: 1, occupants: [] },
  { number: 'B-301', block: 'Block B', floor: 3, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['David N.', 'Kelechi U.'] },
  { number: 'B-302', block: 'Block B', floor: 3, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'B-303', block: 'Block B', floor: 3, status: 'Maintenance', type: 'Single', capacity: 1, occupants: [] },
  { number: 'B-304', block: 'Block B', floor: 3, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Seyi A.', 'Victor E.'] },
  { number: 'B-305', block: 'Block B', floor: 3, status: 'Available', type: 'Double', capacity: 2, occupants: [] },

  // Block A (The Lantern)
  { number: 'A-101', block: 'Block A', floor: 1, status: 'Available', type: 'Four-person', capacity: 4, occupants: [] },
  { number: 'A-102', block: 'Block A', floor: 1, status: 'Occupied', type: 'Four-person', capacity: 4, occupants: ['Tunde B.', 'Gideon M.', 'Babatunde S.', 'Umar K.'] },
  { number: 'A-103', block: 'Block A', floor: 1, status: 'Maintenance', type: 'Single', capacity: 1, occupants: [] },
  { number: 'A-104', block: 'Block A', floor: 1, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'A-201', block: 'Block A', floor: 2, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'A-202', block: 'Block A', floor: 2, status: 'Occupied', type: 'Single', capacity: 1, occupants: ['Adekunle O.'] },
  { number: 'A-204', block: 'Block A', floor: 2, status: 'Occupied', type: 'Four-person', capacity: 4, occupants: ['Daniel Mensah', 'Kunle F.', 'Aliyu S.', 'John D.'] },
  { number: 'A-301', block: 'Block A', floor: 3, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Femi L.', 'Ahmed R.'] },
  { number: 'A-302', block: 'Block A', floor: 3, status: 'Available', type: 'Double', capacity: 2, occupants: [] },

  // Block D (Aster Court)
  { number: 'D-101', block: 'Block D', floor: 1, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'D-102', block: 'Block D', floor: 1, status: 'Occupied', type: 'Double', capacity: 2, occupants: ['Fatima Z.', 'Blessing O.'] },
  { number: 'D-201', block: 'Block D', floor: 2, status: 'Occupied', type: 'Single', capacity: 1, occupants: ['Grace M.'] },
  { number: 'D-202', block: 'Block D', floor: 2, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
  { number: 'D-301', block: 'Block D', floor: 3, status: 'Available', type: 'Double', capacity: 2, occupants: [] },
];

export const initialRequests: AllocationRequest[] = [
  {
    id: 'req-1',
    student: {
      name: 'Daniel Mensah',
      regNo: 'EEE/21/0881',
      department: 'Electrical Engineering',
      level: '400 Level',
      initials: 'DM',
      allocationStatus: 'Pending review',
      room: 'A-204',
      matchScore: 91,
      paymentStatus: 'Cleared',
    },
    department: 'Electrical Engineering',
    matchScore: 91,
    room: 'A-204',
    requestedHostel: 'The Lantern (Block A)',
    status: 'Pending',
    submissionDate: 'Aug 28, 2026',
    notes: 'Requested lower floor due to heavy lab equipment; matched with night study group.',
  },
  {
    id: 'req-2',
    student: {
      name: 'Zainab Bello',
      regNo: 'LIT/23/0314',
      department: 'English & Literary Studies',
      level: '200 Level',
      initials: 'ZB',
      allocationStatus: 'Pending review',
      room: 'D-202',
      matchScore: 87,
      paymentStatus: 'Cleared',
    },
    department: 'English & Literary Studies',
    matchScore: 87,
    room: 'D-202',
    requestedHostel: 'Aster Court (Block D)',
    status: 'Pending',
    submissionDate: 'Aug 29, 2026',
    notes: 'Strict quiet hours preference (10pm to 6am); prefers ensuite room.',
  },
  {
    id: 'req-3',
    student: {
      name: 'Ifeanyi Nwosu',
      regNo: 'MEC/22/0556',
      department: 'Mechanical Engineering',
      level: '300 Level',
      initials: 'IN',
      allocationStatus: 'Allocated',
      room: 'B-102',
      matchScore: 78,
      paymentStatus: 'Pending',
    },
    department: 'Mechanical Engineering',
    matchScore: 78,
    room: 'B-102',
    requestedHostel: 'Mango House (Block B)',
    status: 'Review',
    submissionDate: 'Aug 25, 2026',
    notes: 'Payment verification pending bank clearing confirmation receipt.',
  },
  {
    id: 'req-4',
    student: {
      name: 'Nadia Yusuf',
      regNo: 'MED/21/0142',
      department: 'Medicine & Surgery',
      level: '500 Level',
      initials: 'NY',
      allocationStatus: 'Pending review',
      room: 'B-103',
      matchScore: 73,
      paymentStatus: 'Cleared',
    },
    department: 'Medicine & Surgery',
    matchScore: 73,
    room: 'B-103',
    requestedHostel: 'Mango House (Block B)',
    status: 'Flagged',
    submissionDate: 'Aug 27, 2026',
    notes: 'Target room B-103 currently under maintenance hold for air conditioning repairs.',
  },
  {
    id: 'req-5',
    student: {
      name: 'Chisom Eze',
      regNo: 'ARC/23/1107',
      department: 'Architecture',
      level: '200 Level',
      initials: 'CE',
      allocationStatus: 'Pending review',
      room: 'B-201',
      matchScore: 84,
      paymentStatus: 'Cleared',
    },
    department: 'Architecture',
    matchScore: 84,
    room: 'B-201',
    requestedHostel: 'Mango House (Block B)',
    status: 'Pending',
    submissionDate: 'Aug 30, 2026',
    notes: 'Large drafting board required; requested corner double room.',
  },
  {
    id: 'req-6',
    student: {
      name: 'Victory Okafor',
      regNo: 'CSC/22/1048',
      department: 'Computer Science',
      level: '300 Level',
      initials: 'VO',
      allocationStatus: 'Allocated',
      room: 'B-214',
      matchScore: 94,
      paymentStatus: 'Cleared',
    },
    department: 'Computer Science',
    matchScore: 94,
    room: 'B-214',
    requestedHostel: 'Mango House (Block B)',
    status: 'Approved',
    submissionDate: 'Aug 22, 2026',
    notes: 'Allocated to B-214 (Double room, 2nd floor, matched study hours).',
  },
];

export const roommateCandidates: import('./types').RoommateCandidate[] = [
  {
    id: 'rm-1',
    name: 'Farouk Mustapha',
    regNo: 'CSC/22/1192',
    department: 'Computer Science',
    level: '300 Level',
    initials: 'FM',
    compatibilityScore: 96,
    sleepSchedule: 'Night owl (12am to 7am)',
    studyHabit: 'Quiet focused coding & group discussions',
    cleanliness: 5,
    noiseTolerance: 'Moderate / Headphones preferred',
    preferredBlock: 'Block B (Mango House)',
    bio: 'Software dev major building distributed systems. Clean, quiet study hours, enjoys occasional gaming and weekend hackathons.',
    requestStatus: 'Accepted',
  },
  {
    id: 'rm-2',
    name: 'Somtochukwu Obi',
    regNo: 'CSC/22/1420',
    department: 'Computer Science',
    level: '300 Level',
    initials: 'SO',
    compatibilityScore: 92,
    sleepSchedule: 'Night owl (11pm to 6:30am)',
    studyHabit: 'Late night library research',
    cleanliness: 4,
    noiseTolerance: 'High tolerance with background lo-fi',
    preferredBlock: 'Block B (Mango House)',
    bio: 'Cybersecurity track. Neat desk habit, loves anime, quiet during designated floor study hours.',
    requestStatus: 'None',
  },
  {
    id: 'rm-3',
    name: 'Tobi Adeleke',
    regNo: 'SWE/22/0941',
    department: 'Software Engineering',
    level: '300 Level',
    initials: 'TA',
    compatibilityScore: 88,
    sleepSchedule: 'Flexible (11:30pm to 7:00am)',
    studyHabit: 'Desk study with headphones',
    cleanliness: 4,
    noiseTolerance: 'Low / Prefers pin-drop quiet after 10pm',
    preferredBlock: 'Block B (Mango House)',
    bio: 'Frontend enthusiast. Keeps communal spaces tidy, values early morning quiet reading.',
    requestStatus: 'None',
  },
  {
    id: 'rm-4',
    name: 'Kelechi Amadi',
    regNo: 'EEE/22/0612',
    department: 'Electrical Engineering',
    level: '300 Level',
    initials: 'KA',
    compatibilityScore: 84,
    sleepSchedule: 'Early bird (10pm to 5:30am)',
    studyHabit: 'Early morning circuit theory study',
    cleanliness: 5,
    noiseTolerance: 'Moderate',
    preferredBlock: 'Block A (The Lantern)',
    bio: 'Hardware engineer. Non-smoker, orderly bed arrangement, quiet evening habits.',
    requestStatus: 'Received',
  },
  {
    id: 'rm-5',
    name: 'Ezekiel Bassey',
    regNo: 'MTH/23/0411',
    department: 'Mathematics',
    level: '200 Level',
    initials: 'EB',
    compatibilityScore: 79,
    sleepSchedule: 'Night owl (1am to 8am)',
    studyHabit: 'Whiteboard math problem sessions',
    cleanliness: 3,
    noiseTolerance: 'Moderate / Discussion friendly',
    preferredBlock: 'Block B (Mango House)',
    bio: 'Math & Algorithms enthusiast. Looking for a tech-focused roommate who appreciates late brainstorms.',
    requestStatus: 'None',
  },
];

export const initialMaintenanceTickets: import('./types').MaintenanceTicket[] = [
  {
    id: 'TICK-8024',
    category: 'HVAC & Fan',
    roomNumber: 'B-103',
    block: 'Block B',
    reportedBy: 'Nadia Yusuf',
    reportedByRegNo: 'MED/21/0142',
    priority: 'High',
    status: 'In Progress',
    description: 'Ceiling fan capacitor faulty; making loud grinding noise and running at low rpm.',
    createdAt: '2026-08-28 09:30',
    updatedAt: '2026-08-30 14:15',
    assignedTechnician: 'Mr. Alabi (Senior Electrician)',
    resolutionNotes: 'Replacement 2.5uF capacitor ordered from central warehouse. ETA 24 hours.',
  },
  {
    id: 'TICK-8025',
    category: 'Plumbing',
    roomNumber: 'A-103',
    block: 'Block A',
    reportedBy: 'Adekunle O.',
    reportedByRegNo: 'CSC/21/0084',
    priority: 'Urgent',
    status: 'In Progress',
    description: 'Shower mixer tap leaking heavily causing water accumulation near entryway.',
    createdAt: '2026-08-29 11:00',
    updatedAt: '2026-08-31 08:45',
    assignedTechnician: 'Mallam Kabir (Head Plumber)',
    resolutionNotes: 'Main valve isolated. Gasket and valve stem replacement underway.',
  },
  {
    id: 'TICK-8026',
    category: 'Electrical',
    roomNumber: 'B-214',
    block: 'Block B',
    reportedBy: 'Victory Okafor',
    reportedByRegNo: 'CSC/22/1048',
    priority: 'Medium',
    status: 'Resolved',
    description: 'Study desk power strip surge protector trip reset requested.',
    createdAt: '2026-08-26 16:20',
    updatedAt: '2026-08-27 10:00',
    assignedTechnician: 'Mr. Alabi (Senior Electrician)',
    resolutionNotes: 'Replaced with heavy-duty surge-suppressed 4-way outlet unit. Tested and confirmed.',
  },
  {
    id: 'TICK-8027',
    category: 'Doors & Locks',
    roomNumber: 'D-102',
    block: 'Block D',
    reportedBy: 'Blessing O.',
    reportedByRegNo: 'BIO/23/0771',
    priority: 'Medium',
    status: 'Open',
    description: 'Keypad lock cylinder requires lubrication; sticking on door closure.',
    createdAt: '2026-08-31 15:40',
    updatedAt: '2026-08-31 15:40',
    assignedTechnician: 'Unassigned',
  },
];

export const technicians = [
  { id: 'tech-1', name: 'Mr. Alabi Ojo', specialty: 'Electrical & Solar Backup', phone: '+234 803 441 9021', activeTickets: 2 },
  { id: 'tech-2', name: 'Mallam Kabir Danjuma', specialty: 'Plumbing & Water Systems', phone: '+234 802 918 3342', activeTickets: 3 },
  { id: 'tech-3', name: 'Engr. Emeka Nwankwo', specialty: 'Carpentry & Locksmith', phone: '+234 814 550 7819', activeTickets: 1 },
  { id: 'tech-4', name: 'Mrs. Folake Davies', specialty: 'Sanitation & Facilities', phone: '+234 805 229 1104', activeTickets: 0 },
];

export const defaultBatchConfig: import('./types').BatchAllocationConfig = {
  prioritizeCohort: true,
  prioritizeStudyHours: true,
  seniorityWeight: 4,
  strictPaymentClearance: true,
  balanceFloorLoads: true,
};

export const initialPaymentReceipts: import('./types').PaymentReceipt[] = [
  {
    id: 'REC-2026-081',
    studentName: 'Victory Okafor',
    regNo: 'CSC/22/1048',
    department: 'Computer Science',
    level: '300 Level',
    amountPaid: 185000,
    expectedAmount: 185000,
    paymentDate: '2026-08-22',
    paymentChannel: 'School Portal (Remita RRR)',
    referenceNo: 'RRR-2608-9941-1048',
    session: '2026/2027 Session',
    hostelName: 'Mango House (Block B)',
    roomNumber: 'B-214',
    feeType: 'Full Accommodation Package',
    receiptFileName: 'Victory_Okafor_Hostel_Receipt_2026.pdf',
    receiptFileSize: '1.4 MB',
    status: 'Approved',
    submittedAt: '2026-08-22 14:32',
    verifiedAt: '2026-08-23 09:15',
    verifiedBy: 'Bursar G. Adeleke (Campus Finance)',
    bankName: 'Zenith Bank PLC / Remita Gateway',
    payerName: 'Victory Okafor',
    adminNotes: 'RRR confirmed against Central University Bursary Ledger. Full tariff cleared.',
  },
  {
    id: 'REC-2026-082',
    studentName: 'Daniel Mensah',
    regNo: 'EEE/21/0881',
    department: 'Electrical Engineering',
    level: '400 Level',
    amountPaid: 145000,
    expectedAmount: 145000,
    paymentDate: '2026-08-28',
    paymentChannel: 'School Portal (Remita RRR)',
    referenceNo: 'RRR-2608-4421-0881',
    session: '2026/2027 Session',
    hostelName: 'The Lantern (Block A)',
    roomNumber: 'A-204',
    feeType: 'Hostel Accommodation Fee',
    receiptFileName: 'Daniel_Mensah_Remita_eReceipt.pdf',
    receiptFileSize: '890 KB',
    status: 'Approved',
    submittedAt: '2026-08-28 10:11',
    verifiedAt: '2026-08-28 16:40',
    verifiedBy: 'Bursar G. Adeleke (Campus Finance)',
    bankName: 'First Bank of Nigeria / School Portal',
    payerName: 'Daniel Mensah',
    adminNotes: 'Verified via Remita gateway batch reconciliation.',
  },
  {
    id: 'REC-2026-083',
    studentName: 'Ifeanyi Nwosu',
    regNo: 'MEC/22/0556',
    department: 'Mechanical Engineering',
    level: '300 Level',
    amountPaid: 185000,
    expectedAmount: 185000,
    paymentDate: '2026-08-29',
    paymentChannel: 'Direct Bank Deposit',
    referenceNo: 'TXN-GTB-89201948',
    session: '2026/2027 Session',
    hostelName: 'Mango House (Block B)',
    roomNumber: 'B-102',
    feeType: 'Full Accommodation Package',
    receiptFileName: 'Ifeanyi_GTBank_Teller_Deposit.jpg',
    receiptFileSize: '2.1 MB',
    status: 'Pending',
    submittedAt: '2026-08-29 15:45',
    bankName: 'Guaranty Trust Bank (Campus Branch)',
    payerName: 'Nwosu Chukwuemeka (Guardian)',
    adminNotes: 'Awaiting branch bank statement validation.',
  },
  {
    id: 'REC-2026-084',
    studentName: 'Zainab Bello',
    regNo: 'LIT/23/0314',
    department: 'English & Literary Studies',
    level: '200 Level',
    amountPaid: 215000,
    expectedAmount: 215000,
    paymentDate: '2026-08-29',
    paymentChannel: 'School Portal (Remita RRR)',
    referenceNo: 'RRR-2608-8832-0314',
    session: '2026/2027 Session',
    hostelName: 'Aster Court (Block D)',
    roomNumber: 'D-202',
    feeType: 'Full Accommodation Package',
    receiptFileName: 'Zainab_Bello_AsterCourt_Clearance.pdf',
    receiptFileSize: '1.1 MB',
    status: 'Pending',
    submittedAt: '2026-08-29 17:02',
    bankName: 'United Bank for Africa (UBA)',
    payerName: 'Zainab Bello',
  },
  {
    id: 'REC-2026-085',
    studentName: 'Chisom Eze',
    regNo: 'ARC/23/1107',
    department: 'Architecture',
    level: '200 Level',
    amountPaid: 185000,
    expectedAmount: 185000,
    paymentDate: '2026-08-30',
    paymentChannel: 'Interswitch / WebPay',
    referenceNo: 'ISW-WEB-903184',
    session: '2026/2027 Session',
    hostelName: 'Mango House (Block B)',
    roomNumber: 'B-201',
    feeType: 'Full Accommodation Package',
    receiptFileName: 'Chisom_WebPay_PaymentReceipt.png',
    receiptFileSize: '740 KB',
    status: 'Pending',
    submittedAt: '2026-08-30 08:30',
    bankName: 'Access Bank PLC',
    payerName: 'Chisom Eze',
  },
  {
    id: 'REC-2026-086',
    studentName: 'Ezekiel Bassey',
    regNo: 'MTH/23/0411',
    department: 'Mathematics',
    level: '200 Level',
    amountPaid: 120000,
    expectedAmount: 185000,
    paymentDate: '2026-08-30',
    paymentChannel: 'School Portal (Remita RRR)',
    referenceNo: 'RRR-2608-0012-0411',
    session: '2026/2027 Session',
    hostelName: 'Mango House (Block B)',
    roomNumber: 'B-203',
    feeType: 'Hostel Accommodation Fee',
    receiptFileName: 'Ezekiel_Partial_Hostel_Fee.pdf',
    receiptFileSize: '980 KB',
    status: 'Rejected',
    submittedAt: '2026-08-30 11:20',
    verifiedAt: '2026-08-31 09:00',
    verifiedBy: 'Bursar G. Adeleke (Campus Finance)',
    bankName: 'Stanbic IBTC Bank',
    payerName: 'Ezekiel Bassey',
    rejectionReason: 'Tariff discrepancy: Double room rate for Mango House is ₦185,000. Submitted receipt reflects a partial payment of ₦120,000.',
    adminNotes: 'Please pay the outstanding ₦65,000 balance on the student portal and submit the combined receipt for final clearance.',
  },
];

export const initialNotifications: import('./types').AppNotification[] = [
  {
    id: 'notif-1',
    recipientRegNo: 'CSC/22/1048',
    title: 'Fee Payment Verified & Cleared',
    message: 'Your hostel accommodation payment of ₦185,000 (RRR-2608-9941-1048) has been officially verified by the University Bursary. Your Digital Clearance Pass is ready!',
    type: 'payment_approved',
    read: false,
    timestamp: 'Aug 23, 2026 · 09:15 AM',
    actionUrl: '/student/payments',
  },
  {
    id: 'notif-2',
    recipientRegNo: 'CSC/22/1048',
    title: 'Mutual Roommate Pair Confirmed',
    message: 'Farouk Mustapha (CSC/22/1192) accepted your pairing invitation for Room B-214 with a 96% lifestyle compatibility score.',
    type: 'roommate_match',
    read: false,
    timestamp: 'Aug 24, 2026 · 02:40 PM',
    actionUrl: '/student/roommates',
  },
  {
    id: 'notif-3',
    recipientRegNo: 'CSC/22/1048',
    title: 'Room Allocation Finalized',
    message: 'Official bed space allocation confirmed: Mango House (Block B), Room B-214 (Double room, 2nd floor).',
    type: 'allocation_update',
    read: true,
    timestamp: 'Aug 22, 2026 · 11:00 AM',
    actionUrl: '/student',
  },
  {
    id: 'notif-4',
    recipientRegNo: 'CSC/22/1048',
    title: 'Maintenance Ticket Resolved',
    message: 'Ticket TICK-8026 for Room B-214 electrical surge unit has been serviced and resolved by Mr. Alabi.',
    type: 'maintenance',
    read: true,
    timestamp: 'Aug 27, 2026 · 10:00 AM',
    actionUrl: '/student/maintenance',
  },
];


